version: '3'

services:
  hybris_image_builder:
    build:
      context: ./path/to/dockerfile/directory
      dockerfile: Dockerfile
    image: hybris:1905

  hybris_container:
    image: hybris:1905
    ports:
      - "9001:9001"
      - "9002:9002"
      - "8000:8000"
    command: ./hybrisserver.sh debug
    depends_on:
      - hybris_image_builder
